package com.homedepot.hr.hr.staffingforms.dto;
/* 
 * This program is proprietary to The Home Depot and is not to be
 * reproduced, used, or disclosed without permission of:
 *    
 *  The Home Depot
 *  2455 Paces Ferry Road, N.W.
 *  Atlanta, GA 30339-4053
 *
 * File Name: CalendarDaySummary.java
 * Application: RetailStaffing
 */
import java.io.Serializable;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * This class represents represent the breakdown of interview slots by status for a given day
 * <br>
 * Using the XStream API to marshal this object into an XML will produce the following
 * format:<br>
 * <br>
 * <code>
 * &lt;daySummary&gt;<br>
 * &nbsp;&lt;date&gt;&lt;/date&gt;<br>
 * &nbsp;&lt;dayOfWeekIndicator&gt;&lt;/dayOfWeekIndicator&gt;<br>
 * &nbsp;&lt;slotSummaries&gt;<br>
 * &nbsp;.<br>
 * &nbsp;.<br>
 * &nbsp;&lt;/slotSummaries&gt;<br>
 * &lt;/daySummary&gt;<br>
 * </code>
 * <br>
 * Only non-null member variables will be present in the XML generated by
 * the XStream API.
 * 
 * @see StatusSlotSummary
 */
@XStreamAlias("daySummary")
public class DaySummary implements Serializable
{
    private static final long serialVersionUID = 1283675876160425277L;

    // date the summary is for
    @XStreamAlias("date")
    private Date mDate;
    
    //Added as part of Flex to HTML Conversion - 12 May 2015
    @XStreamAlias("formattedDate")
    private String formattedDate;
    // day of the week, 1 = Sunday, 2 = Monday... 7 = Saturday
    @XStreamAlias("dayOfWeekIndicator")
    private int mDayOfWeekIndicator;

    // collection of status slot summary objects
    @XStreamAlias("slotSummaries")
    private List<StatusSlotSummary> mSlotSummaries;
    
    //Added as part of Flex to HTML Conversion - 12 May 2015
    @XStreamAlias("StatusSlotCountDtls")
    private List<StatusSlotCountDtl> mSlotCountDtls;
    
	/**
     * @return the date this summary is for
     */
    public Date getDate()
    {
    	return mDate;
    } // end function getDate()
    
    /**
     * @param date the date this summary is for
     */
    public void setDate(Date date)
    {
    	mDate = date;
    } // end function setDate()
    
    /**
     * @return day of the week, 1 = Sunday, 2 = Monday... 7 = Saturday
     */
    public int getDayOfWeekIndicator()
    {
    	return mDayOfWeekIndicator;
    } // end function getDayOfWeekIndicator()
    
    /**
     * @param dayOfWeekIndicator day of the week
     */
    public void setDayOfWeekIndicator(int dayOfWeekIndicator)
    {
    	mDayOfWeekIndicator = dayOfWeekIndicator;
    } // end function setDayOfWeekIndicator()
    
    /**
     * @return collection of status slot summary objects
     */
    public List<StatusSlotSummary> getSlotSummaries()
    {
    	return mSlotSummaries;
    } // end function getSlotSummaries()
    
    /**
     * @param summaries collection of status slot summary objects
     */
    public void setSlotSummaries(List<StatusSlotSummary> summaries)
    {
    	mSlotSummaries = summaries;
    } // end function setSlotSummaries()
    
    /**
     * @param summary status slot summary object
     */
    public void addSlotSummary(StatusSlotSummary summary)
    {
    	if(mSlotSummaries == null){ mSlotSummaries = new ArrayList<StatusSlotSummary>(); }
    	mSlotSummaries.add(summary);
    } // end function addSlotSummary()

    //Start - Added as part of Flex to HTML Conversion - 12 May 2015
    /**
     * @return formattedDate
     */
	public String getFormattedDate() {
		return formattedDate;
	}

	/**
	 * @param formattedDate
	 */
	public void setFormattedDate(String formattedDate) {
		this.formattedDate = formattedDate;
	}
	
	/**
	 * @return collection of StatusSlotCountDtl objects
	 */
	public List<StatusSlotCountDtl> getmSlotCountDtls() {
		return mSlotCountDtls;
	}

	/**
	 * @param mSlotCountDtls
	 */
	public void setmSlotCountDtls(List<StatusSlotCountDtl> mSlotCountDtls) {
		this.mSlotCountDtls = mSlotCountDtls;
	}
	//End - Added as part of Flex to HTML Conversion - 12 May 2015
    
} // end class DaySummary