package com.homedepot.hr.hr.staffingforms.dto;
/* 
 * This program is proprietary to The Home Depot and is not to be
 * reproduced, used, or disclosed without permission of:
 *    
 *  The Home Depot
 *  2455 Paces Ferry Road, N.W.
 *  Atlanta, GA 30339-4053
 *
 * File Name: RequisitionSchedule.java
 * Application: RetailStaffing
 */
import java.io.Serializable;
import java.sql.Timestamp;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * This class represents a requisition calendar time slot that can be used to schedule interviews.
 * <br>
 * Using the XStream API to marshal this object into an XML will produce the following format:<br>
 * <br>
 * <code>
 * &lt;requisitionSchedule&gt;<br>
 * &nbsp;&lt;statusCode&gt;&lt;/statusCode&gt;<br>
 * &nbsp;&lt;calendarId&gt;&lt;/calendarId&gt;<br>
 * &nbsp;&lt;beginTimestamp&gt;&lt;/beginTimestamp&gt;<br>
 * &nbsp;&lt;createTimestamp&gt;&lt;/createTimestamp&gt;<br>
 * &nbsp;&lt;createSystemUserId&gt;&lt;/createSystemUserId&gt;<br>
 * &nbsp;&lt;lastUpdateSystemUserId&gt;&lt;/lastUpdateSystemUserId&gt;<br>
 * &nbsp;&lt;lastUpdateTimestamp&gt;&lt;/lastUpdateTimestamp&gt;<br>
 * &nbsp;&lt;storeNumber&gt;&lt;/storeNumber&gt;<br>
 * &nbsp;&lt;sequenceNumber&gt;&lt;/sequenceNumber&gt;<br>
 * &nbsp;&lt;requisitionScheduleStatusCode&gt;&lt;/requisitionScheduleStatusCode&gt;<br>
 * &nbsp;&lt;requisitionScheduleReservationTimestamp&gt;&lt;/requisitionScheduleReservationTimestamp&gt;<br>
 * &nbsp;&lt;phoneScreenId&gt;&lt;/phoneScreenId&gt;<br>
 * &nbsp;&lt;candidateName&gt;&lt;/candidateName&gt;<br>
 * &lt;/requisitionSchedule&gt;<br>
 * </code>
 * <br>
 * Only non-null member variables will be present in the XML generated by
 * the XStream API.
 */
@XStreamAlias("requisitionSchedule")
public class RequisitionSchedule implements Serializable
{
    private static final long serialVersionUID = 398381622149917693L;

    /** requisition calendar id */
    @XStreamAlias("calendarId")
    private int mCalendarId;
    /** begin timestamp */
    @XStreamAlias("beginTimestamp")
    private Timestamp mBgnTs;
    /** create timestamp */
    @XStreamAlias("createTimestamp")
    private Timestamp mCrtTs;
    /** create system user id */
    @XStreamAlias("createSystemUserId")
    private String mCrtSysUsrId;
    /** last update system user id */
    @XStreamAlias("lastUpdateSystemUserId")
    private String mLastUpdSysUsrId;
    /** last update timestamp */
    @XStreamAlias("lastUpdateTimestamp")
    private Timestamp mLastUpdTs;
    /** store number */
    @XStreamAlias("storeNumber")
    private String mStrNbr;
    /** sequence number */
    @XStreamAlias("sequenceNumber")
    private short mSeqNbr;
    /** requisition schedule status code */
    @XStreamAlias("requisitionScheduleStatusCode")
    private Short mReqnSchStatCd;
    /** requisition schedule reservation timestamp */
    @XStreamAlias("requisitionScheduleReservationTimestamp")
    private Timestamp mReqnSchRsrvTs;
    /** phone screen id */
    @XStreamAlias("phoneScreenId")
    private Integer mPhnScrnId;
    /** name of the candidate attached to this block (if an interview has been scheduled */
    @XStreamAlias("candidateName")
    private String mCandidateName;
    /** location the requisition is for */
    @XStreamAlias("requisitionLocation")
    private String mRequisitionLocation;
    /** Internal or External candidate */
    @XStreamAlias("candidateType")
    private String mCandidateType;
    
    /**
     * @return the requisition calendar id
     */
	public int getCalendarId()
	{
		return mCalendarId;
	} // end function getCalendarId()

	/**
	 * @param calendarId the requisition calendar id
	 */
	public void setCalendarId(int calendarId)
	{
		mCalendarId = calendarId;
	} // end function setCalendarId()
	
	/**
	 * @return the create timestamp
	 */
	public Timestamp getCrtTs()
	{
		return mCrtTs;
	} // end function getCrtTs()
	
	/**
	 * @param crtTs the create timestamp
	 */
	public void setCrtTs(Timestamp crtTs)
	{
		mCrtTs = crtTs;
	} // end function setCrtTs()

	/**
	 * @return the create system user id
	 */
	public String getCrtSysUsrId()
	{
		return mCrtSysUsrId;
	} // end function getCrtSysUsrId()
	
	/**
	 * @param crtSysUsrId the create system user id
	 */
	public void setCrtSysUsrId(String crtSysUsrId)
	{
		mCrtSysUsrId = crtSysUsrId;
	} // end function setCrtSysUsrId()

	/**
	 * @return the begin timestamp
	 */
	public Timestamp getBgnTs()
	{
		return mBgnTs;
	} // end function getBgnTs()
	
	/**
	 * @param bgnTs the begin timestamp
	 */
	public void setBgnTs(Timestamp bgnTs)
	{
		mBgnTs = bgnTs;
	} // end function setBgnTs()

	/**
	 * @return the last update system user id
	 */
	public String getLastUpdSysUsrId()
	{
		return mLastUpdSysUsrId;
	} // end function getLastUpdSysUsrId()
	
	/**
	 * @param lastUpdSysUsrId the last update system user id
	 */
	public void setLastUpdSysUsrId(String lastUpdSysUsrId)
	{
		mLastUpdSysUsrId = lastUpdSysUsrId;
	} // end function setLastUpdSysUsrId()

	/**
	 * @return the last update timestamp
	 */
	public Timestamp getLastUpdTs()
	{
		return mLastUpdTs;
	} // end function getLastUpdTs()
	
	/**
	 * @param lastUpdTs the last update timestamp
	 */
	public void setLastUpdTs(Timestamp lastUpdTs)
	{
		mLastUpdTs = lastUpdTs;
	} // end function setLastUpdTs()

	/**
	 * @return the store number
	 */
	public String getStrNbr()
	{
		return mStrNbr;
	} // end function getStrNbr()

	/**
	 * @param strNbr the store number
	 */
	public void setStrNbr(String strNbr)
	{
		mStrNbr = strNbr;
	} // end function setStrNbr()

	/**
	 * @return the sequence number
	 */
	public short getSeqNbr() 
	{
		return mSeqNbr;
	} // end function getSeqNbr()
	
	/**
	 * @param seqNbr the sequence number
	 */
	public void setSeqNbr(short seqNbr)
	{
		mSeqNbr = seqNbr;
	} // end function setSeqNbr()
	
	/**
	 * @return the requisition schedule status code
	 */
	public Short getReqnSchStatCd()
	{
		return mReqnSchStatCd;
	} // end function getReqnSchStatCd()
	
	/**
	 * @param reqnSchStatCd the requisition schedule status code
	 */
	public void setReqnSchStatCd(Short reqnSchStatCd)
	{
		mReqnSchStatCd = reqnSchStatCd;
	} // end function setReqnSchStatCd()
	
	/**
	 * @return the requisition schedule reservation timestamp
	 */
	public Timestamp getReqnSchRsrvTs()
	{
		return mReqnSchRsrvTs;
	} // end function getReqnSchRsrvTs()
	
	/**
	 * @param reqnSchRsrvTs the requisition schedule reservation timestamp
	 */
	public void setReqnSchRsrvTs(Timestamp reqnSchRsrvTs)
	{
		mReqnSchRsrvTs = reqnSchRsrvTs;
	} // end function setReqnSchRsrvTs()
	
	/**
	 * @return the phone screen id
	 */
	public Integer getPhnScrnId()
	{
		return mPhnScrnId;
	} // end function getPhnScrnId()
	
	/**
	 * @param phnScrnId the phone screen id
	 */
	public void setPhnScrnId(Integer phnScrnId)
	{
		mPhnScrnId = phnScrnId;
	} // end function setPhnScrnId()
	
	/**
	 * @return name of the candidate attached to this block (if an interview has been scheduled
	 */
	public String getCandidateName()
	{
		return mCandidateName;
	} // end function getCandidateName()
	
	/**
	 * @param candidateName name of the candidate attached to this block (if an interview has been scheduled
	 */
	public void setCandidateName(String candidateName)
	{
		mCandidateName = candidateName;
	} // end function setCandidateName()
	
	/**
	 * @return store that the requisition is for based on the candidate attached to this block (if an interview has been scheduled)
	 */
	public String getRequisitionLocation()
	{
		return mRequisitionLocation;
	} // end function getRequisitionLocation()
	
	/**
	 * @param store that the requisition is for based on the candidate attached to this block (if an interview has been scheduled)
	 */
	public void setRequisitionLocation(String requisitionLocation)
	{
		mRequisitionLocation = requisitionLocation;
	} // end function setRequisitionLocation()	
	
	/**
	 * @return Internal or External candidate attached to this block (if an interview has been scheduled)
	 */
	public String getCandidateType()
	{
		return mCandidateType;
	} // end function getCandidateType()
	
	/**
	 * @param Internal or External candidate attached to this block (if an interview has been scheduled)
	 */
	public void setCandidateType(String candidateType)
	{
		mCandidateType = candidateType;
	} // end function setCandidateType()
	

} // end class RequisitionSchedule