package com.homedepot.hr.hr.staffingforms.dto;
/* 
 * This program is proprietary to The Home Depot and is not to be
 * reproduced, used, or disclosed without permission of:
 *    
 *  The Home Depot
 *  2455 Paces Ferry Road, N.W.
 *  Atlanta, GA 30339-4053
 *
 * File Name: StatusSlotSummary.java
 * Application: RetailStaffing
 */
import java.io.Serializable;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * This class represents the number of interview slots that have a particular status. This is
 * used in conjunction with the DaySummary class to represent the breakdown of interview slots 
 * by status for a given day
 * <br>
 * Using the XStream API to marshal this object into an XML will produce the following format:<br>
 * <br>
 * <code>
 * &lt;slotSummary&gt;<br>
 * &nbsp;&lt;statusCode&gt;&lt;/statusCode&gt;<br>
 * &nbsp;&lt;slotCount&gt;&lt;/slotCount&gt;<br>
 * &lt;/slotSummary&gt;<br>
 * </code>
 * <br>
 * Only non-null member variables will be present in the XML generated by
 * the XStream API.
 */
@XStreamAlias("slotSummary")
public class StatusSlotSummary implements Serializable
{   
    private static final long serialVersionUID = -2025300045320098891L;
    
    // interview slot status code
	@XStreamAlias("statusCode")
	private short mStatusCode;
	// number of interview slots that have the status
	@XStreamAlias("slotCount")
	private int mSlotCount;
	
	/**
	 * constructor
	 * 
	 * @param statusCode interview slot status code
	 * @param slotCount count of interview slots that have the status
	 */
	public StatusSlotSummary(short statusCode, int slotCount)
	{
		mStatusCode = statusCode;
		mSlotCount = slotCount;
	} // end constructor()
	
	/**
	 * @return interview slot status code
	 */
	public short getStatusCode()
	{
		return mStatusCode;
	} // end function getStatusCode()
	
	/**
	 * @param statusCode interview slot status code
	 */
	public void setStatusCode(short statusCode)
	{
		mStatusCode = statusCode;
	} // end function setStatusCode()
	
	/**
	 * @return number of interview slots that have the status
	 */
	public int getSlotCount()
	{
		return mSlotCount;
	} // end function getSlotCount()
	
	/**
	 * @param slotCount number of interview slots that have the status
	 */
	public void setSlotCount(int slotCount)
	{
		mSlotCount = slotCount;
	} // end function setSlotCount()
} // end class StatusSlotSummary()