package com.homedepot.hr.hr.staffingforms.service.response;
/* 
 * This program is proprietary to The Home Depot and is not to be
 * reproduced, used, or disclosed without permission of:
 *    
 *  The Home Depot
 *  2455 Paces Ferry Road, N.W.
 *  Atlanta, GA 30339-4053
 *
 * File Name: CalendarResponse.java
 * Application: RetailStaffing
 */

import java.util.List;

import com.homedepot.hr.hr.staffingforms.dto.DaySummary;
import com.homedepot.hr.hr.staffingforms.dto.RequisitionSchedule;
import com.homedepot.hr.hr.staffingforms.dto.RequisitionScheduleSlotDtl;
import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * Response object that will be populated and returned whenever a call to the CalendarService
 * is invoked. Using the XStream API to marshal this object into an XML will produce the following
 * format:<br>
 * <br>
 * <code>
 * &lt;calendarResponse&gt;<br>
 * &nbsp;&lt;error&gt;&lt;/error&gt;<br>
 * &nbsp;&lt;numSlotsRequested&gt;&lt;/numSlotsRequested&gt;<br>
 * &nbsp;&lt;numSlotsAffected&gt;&lt;/numSlotsAffected&gt;<br>
 * &nbsp;&lt;daySummaries&gt;&lt;/daySummaries&gt;<br>
 * &nbsp;&lt;requisitionSchedules&gt;&lt;/requisitionSchedules&gt;<br>
 * &lt;/calendarResponse&gt;<br>
 * </code>
 * <br>
 * Only non-null member variables will be present in the XML generated by the XStream API.<br>
 * <br>
 * @see DaySummary
 * @see RequisitionSchedule
 * @see Response
 */
@XStreamAlias("calendarResponse")
public class CalendarResponse extends Response
{
    private static final long serialVersionUID = 7356319870727217260L;
    
    /** number of interview slots provided on an insert/update/delete request */
    @XStreamAlias("numSlotsRequested")
    private Integer mNumSlotsRequested;
    
    /** number of interview slots inserted/updated/deleted as a result of a request */
    @XStreamAlias("numSlotsAffected")
    private Integer mNumSlotsAffected;

    /** collection of day summary objects, populated when a call is made to the /calendarSummary method */
    @XStreamAlias("daySummaries")
    private List<DaySummary> mDaySummaries;
    
    /** collection of requisition schedule objects, populated when a call is made to the /calendarDetails method */
    @XStreamAlias("requisitionSchedules")
    private List<RequisitionSchedule> mSchedules;

    /** calendar ID provided on update/delete request */
    @XStreamAlias("reqnCalId")
    private Integer mReqnCalId;

    /** calendar name provided on update/delete request */
    @XStreamAlias("reqnCalDesc")
    private String mReqnCalDesc;

    //Added as part of  Flex to HTML Conversion - 12 May 2015
    @XStreamAlias("requisitionScheduleSlots")
    private List<RequisitionScheduleSlotDtl> mScheduleSlots;
    /**
     * @return the number of interview slots provided on an insert/update/delete request
     */
    public Integer getNumSlotsRequested()
    {
    	return mNumSlotsRequested;
    } // end function getNumSlotsRequested()
    
    /**
     * @param slotsRequested the number of interview slots provided on an insert/update/delete request
     */
    public void setNumSlotsRequested(Integer slotsRequested)
    {
    	mNumSlotsRequested = slotsRequested;
    } // end function setSlotsProvided()
    
    /**
     * @return the number of interview slots inserted/updated/deleted as a result of a request
     */
    public Integer getNumSlotsAffected()
    {
    	return mNumSlotsAffected;
    } // end function getNumSlotsAffected()

    /**
     * @param slotsAffected the number of interview slots inserted/updated/deleted as a result of a request
     */
    public void setNumSlotsAffected(Integer slotsAffected)
    {
    	mNumSlotsAffected = slotsAffected;
    } // end function setNumSlotsAffected()
    
    /**
     * @param summaries collection of day summary objects
     */
    public void setDaySummaries(List<DaySummary> summaries)
    {
    	mDaySummaries = summaries;
    } // end function setDaySummaries()
    
    /**
     * @return collection of day summary objects
     */
    public List<DaySummary> getDaySummaries()
    {
    	return mDaySummaries;
    } // end function getDaySummaries()
    
    /**
     * @return collection of requisition schedule objects
     */
    public List<RequisitionSchedule> getSchedules()
    {
    	return mSchedules;
    } // end function getSchedules()
    
    /**
     * @param schedules collection of requisition schedule objects
     */
    public void setSchedules(List<RequisitionSchedule> schedules)
    {
    	mSchedules = schedules;
    } // end function setSchedules()
    /**
     * @return the calendar ID sent to be updated as a result of a request
     */
    public Integer getReqnCalId()
    {
    	return mReqnCalId;
    } // end function getReqnCalId()

    /**
     * @param reqnCalId of the calendar sent to be updated as a result of a request
     */
    public void setReqnCalId(Integer reqnCalId)
    {
    	mReqnCalId = reqnCalId;
    } // end function setReqnCalId()
    /**
     * @return the calendar name sent to be updated as a result of a request
     */
    public String getReqnCalDesc()
    {
    	return mReqnCalDesc;
    } // end function getReqnCalDesc()

    /**
     * @param reqnCaldesc of the calendar sent to be updated as a result of a request
     */
    public void setReqnCalDesc(String reqnCalDesc)
    {
    	mReqnCalDesc = reqnCalDesc;
    } // end function setReqnCalDesc()
    
    //Start - Added as part of  Flex to HTML Conversion - 12 May 2015
    /**
     * @return Collection of RequisitionScheduleSlotDtl objects
     */
    public List<RequisitionScheduleSlotDtl> getScheduleSlots() {
		return mScheduleSlots;
	}

    /**
     * @param scheduleSlots
     */
	public void setScheduleSlots(List<RequisitionScheduleSlotDtl> scheduleSlots) {
		this.mScheduleSlots = scheduleSlots;
	}
	//End - Added as part of  Flex to HTML Conversion - 12 May 2015
    
} // end class CalendarResponse