/* Login Actions */
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const USER_PROFILE = 'USER_PROFILE';

/* REQUISITION ACTIONS */
export const GET_REQUISITIONS = 'GET_REQUISITIONS';
export const GET_REQ_ACTIONS = 'GET_REQ_ACTIONS';
export const REQ_ERROR = 'REQ_ERROR';
export const REQ_ACTIONS_RESET = 'REQ_ACTIONS_RESET';
export const REQ_INFO_RESET = 'REQ_INFO_RESET';

/* REQDETAILS ACTIONS */
export const GET_REQ_DETAILS = 'GET_REQ_DETAILS';
export const REQ_DETAILS_ERROR = 'REQ_DETAILS_ERROR';

/* CANDIDATE ACTIONS */
export const GET_CANDIDATES = 'GET_CANDIDATES';
export const CANDIDATE_ERROR = 'CANDIDATE_ERROR';
export const CAND_LIST_RESET = 'CAND_LIST_RESET';

/* ORIENTATION ACTIONS */
export const UPDATE_ORIENTATION = 'UPDATE_ORIENTATION';
export const ORIENTATION_ERROR = 'ORIENTATION_ERROR';

/* ACTIONS NEEDED ACTIONS */
export const ACTIONS_NEEDED = 'ACTIONS_NEEDED';
export const ACTIONS_NEEDED_RESET = 'ACTIONS_NEEDED_RESET';
export const ACTIONS_NEEDED_ERROR = 'ACTIONS_NEEDED_ERROR';

/* STORE ACTIONS */
export const IS_VALID_STORE = 'IS_VALID_STORE';
export const IS_VALID_STORE_ERROR = 'IS_VALID_STORE_ERROR';
export const GET_STORE_ADDRESS = 'GET_STORE_ADDRESS';
export const STORE_ADDRESS_ERROR = 'STORE_ADDRESS_ERROR';

/* CALENDAR ACTIONS */
export const GET_ALL_CALENDAR_DETAILS = 'GET_ALL_CALENDAR_DETAILS';
export const GET_ALL_CALENDAR_DETAILS_ERROR = 'GET_ALL_CALENDAR_DETAILS_ERROR';
